---
title: "04 wordclouds"
output: pdf_document
date: "2023-09-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
library(wordcloud2)
library(tvthemes)
library(wordcloud)
library(RColorBrewer)
library(png)
```

```{r}
rm(list = ls())

if (Sys.info()["user"]=='hugosalas'){
  BASE_PATH = "/Users/hugosalas/Roemer & Salas/"
} else if (Sys.info()["user"]=='aleroemer'){
  BASE_PATH = "~/My Drive/DiscursoUSA_MX/"
}

DATA_PATH =  paste0(BASE_PATH, "data/")
CLEAN_DATA_PATH = paste0(DATA_PATH, "clean/")
UTILS_PATH = paste0(BASE_PATH, "USMEX_TextAnalysis/utils/")

source(str_c(UTILS_PATH, 'data_manipulation_utils.R'))
```

### B. Load all relevant files and DF

```{r}
load(paste0(CLEAN_DATA_PATH, "paragraphs_MEXICO"))
```

### C. Tokenize Paragraphs that mention Mexico
```{r}
tokens_df <- unnest_tokens(paragraphs_df, word_tokens, text_paragraph, token = "words")

#eliminate stopwords
data(stop_words)

# Assuming your dataframe is called 'df' and the column containing the tokens is called 'word_tokens'
tokens_df_nosw <- tokens_df %>%
  anti_join(stop_words, by = c("word_tokens" = "word"))
```


### D. Trump Wordcloud. Try 1
```{r}
#cols <- avatar_pal(palette = "AirNomads",n = 7)

exclude = c("mexico", "u.s", "canada", "applause", "united", "trump", "president", "el")

trump_wcloud <- tokens_df_nosw %>%
  filter(last_name == "Trump") %>%
  count(word_tokens) %>%
  arrange(desc(n)) %>%
  filter(n > 1) %>%
  rename(freq = n) %>% 
  filter(!(word_tokens %in% exclude))

### Without shape
wordcloud2(trump_wcloud,size = 1)

### With colors of Mexican flag
wordcloud2(trump_wcloud, size = 1, color = rep(c("#006847", "#ED2939"),2228))

### With Trump's image as shape -- can't get it to work
### Re-installing package from Git
# Troubleshooting: https://github.com/Lchiffon/wordcloud2/issues/12
#"However, if I re-install the package directly from git rather than cran, it works!"
library(devtools)
devtools::install_github("lchiffon/wordcloud2", force = TRUE)
wordcloud2(trump_wcloud, size = 1,figPath = "images/trump2.png", color = rep(c("#006847", "#ED2939"),2228))


# with different images
wordcloud2(trump_wcloud, size = 1,figPath = "images/trump2.png", color = rep(c("#006847", "#ED2939"),2228))
wordcloud2(trump_wcloud, size = 1,figPath = "images/trump.png", color = rep(c("#006847", "#ED2939"),2228))
wordcloud2(trump_wcloud, size = 1,figPath = "images/trump3.png", color = rep(c("#006847", "#ED2939"),2228))


# improvements
wordcloud2(trump_wcloud, 
           size = 1.3,
           figPath = "images/trump2.png",
           color = rep(c("#006847", "#ED2939"),2228))

#lettercloud
letterCloud(trump_wcloud, word = "TRUMP", color = rep(c("#006847", "#ED2939"),2228))

# Save image

```



# Obama's Wordcloud


```{r}
set.seed(9413)

exclude = c("mexico", "u.s", "canada", "applause", "united", "obama", "president", "el")

obama_wcloud <- tokens_df_nosw %>%
  filter(last_name == "Obama") %>%
  count(word_tokens) %>%
  arrange(desc(n)) %>%
  filter(n > 1) %>%
  rename(freq = n) %>% 
  filter(!(word_tokens %in% exclude))

obama_wcloud <- obama_wcloud %>% 
  filter(!str_detect(word_tokens, "\\d")) #eliminate numbers

### Without shape
wordcloud2(obama_wcloud,size = 1)

### With colors of Mexican flag
wordcloud2(obama_wcloud, size = 1, color = rep(c("#006847", "#ED2939"),2228))

### With Obama's image as shape -- can't get it to work

wordcloud2(obama_wcloud, size = 1,figPath = "images/obama1.png", color = rep(c("#006847", "#ED2939"),2228))


# with different images - Run in console**
wordcloud2(obama_wcloud, size = 1,figPath = "images/obama1.png", color = rep(c("#006847", "#ED2939"),2228))
wordcloud2(obama_wcloud, size = 1,figPath = "images/obama2.png", color = rep(c("#006847", "#ED2939"),2228))
wordcloud2(obama_wcloud, size = 1,figPath = "images/obama3.png", color = rep(c("#006847", "#ED2939"),2228))
wordcloud2(obama_wcloud, size = 1,figPath = "images/obama4.png", color = rep(c("#006847", "#ED2939"),2228))
wordcloud2(obama_wcloud, size = 1,figPath = "images/obama5.jpeg", color = rep(c("#006847", "#ED2939"),2228))
wordcloud2(obama_wcloud, size = 1,figPath = "images/obama6.jpeg", color = rep(c("#006847", "#ED2939"),2228))
wordcloud2(obama_wcloud, size = 1,figPath = "images/obama7.jpeg", color = rep(c("#006847", "#ED2939"),2228))
# eliminate 
wordcloud2(obama_wcloud, 
           size = 1.3,
           figPath = "images/obama1.png",
           color = rep(c("#006847", "#ED2939"),2228))

# lettercloud
letterCloud(obama_wcloud, word = "OBAMA", color = rep(c("#006847", "#ED2939"),2228))
# Save image

```


# George W Bush's Wordcloud

```{r}
set.seed(9413)

exclude = c("mexico", "u.s", "canada", "applause", 
            "united", "bush", "president", "el", "mcclellan", "scott", "el")

bush_wcloud <- tokens_df_nosw %>%
  filter(last_name == "W. Bush") %>%
  count(word_tokens) %>%
  arrange(desc(n)) %>%
  filter(n > 1) %>%
  rename(freq = n) %>% 
  filter(!(word_tokens %in% exclude))

bush_wcloud <- bush_wcloud %>% 
  filter(!str_detect(word_tokens, "\\d")) #eliminate numbers

### Without shape
wordcloud2(bush_wcloud,size = 1)

### With colors of Mexican flag
wordcloud2(bush_wcloud, size = 1, color = rep(c("#006847", "#ED2939"),2228))

### With Obama's image as shape -- can't get it to work

wordcloud2(bush_wcloud, size = 1,figPath = "images/bush1.png", color = rep(c("#006847", "#ED2939"),2228))


# with different images - Run in console**
wordcloud2(bush_wcloud, size = 1,figPath = "images/bush1.png", color = rep(c("#006847", "#ED2939"),2228))
wordcloud2(bush_wcloud, size = 1,figPath = "images/bush2.jpeg", color = rep(c("#006847", "#ED2939"),2228))


# eliminate 
wordcloud2(obama_wcloud, 
           size = 1.3,
           figPath = "images/obama1.png",
           color = rep(c("#006847", "#ED2939"),2228))


#lettercloud
letterCloud(bush_wcloud, word = "W. BUSH", color = rep(c("#006847", "#ED2939"),2228))

# Save image

```


# Biden's Wordcloud

```{r}
set.seed(9413)

exclude = c("mexico", "u.s", "canada", "applause", 
            "united", "biden", "president", "el")

biden_wcloud <- tokens_df_nosw %>%
  filter(last_name == "Biden") %>%
  count(word_tokens) %>%
  arrange(desc(n)) %>%
  filter(n > 1) %>%
  rename(freq = n) %>% 
  filter(!(word_tokens %in% exclude))

biden_wcloud <- biden_wcloud %>% 
  filter(!str_detect(word_tokens, "\\d")) #eliminate numbers

### Without shape
wordcloud2(biden_wcloud,size = 1)

### With colors of Mexican flag
wordcloud2(biden_wcloud, size = 1, color = rep(c("#006847", "#ED2939"),2228))

### With Biden's image as shape -- can't get it to work

wordcloud2(biden_wcloud, size = 1,figPath = "images/biden1.jpeg", color = rep(c("#006847", "#ED2939"),2228))
wordcloud2(biden_wcloud, size = 1,figPath = "images/biden2.jpeg", color = rep(c("#006847", "#ED2939"),2228))#not good
wordcloud2(biden_wcloud, size = 1,figPath = "images/biden3.jpeg", color = rep(c("#006847", "#ED2939"),2228))#not good
wordcloud2(biden_wcloud, size = 1,figPath = "images/biden5.jpeg", color = rep(c("#006847", "#ED2939"),2228))#not good
wordcloud2(biden_wcloud, size = 1,figPath = "images/biden7.jpeg", color = rep(c("#006847", "#ED2939"),2228))#not good
wordcloud2(biden_wcloud, size = 1,figPath = "images/biden9.jpeg", color = rep(c("#006847", "#ED2939"),2228)) #not good
wordcloud2(biden_wcloud, size = 1,figPath = "images/biden10.jpeg", color = rep(c("#006847", "#ED2939"),2228))#possible
wordcloud2(biden_wcloud, size = 1,figPath = "images/biden11.jpeg", color = rep(c("#006847", "#ED2939"),2228))#possible

wordcloud2(biden_wcloud, 
           minSize = 1.3,
           figPath = "images/biden11.jpeg",
           color = rep(c("#006847", "#ED2939"),2228))


#lettercloud
letterCloud(biden_wcloud, word = "BIDEN", color = rep(c("#006847", "#ED2939"),2228))

# Save image

```